import React from 'react';
import CardShell, { CardLabel } from '../ui/CardShell';

export default function AIInsightsCard({ ai }) {
  const sentences = ai.interpretation.split(/(?<=\.)\s+/).filter(Boolean);

  return (
    <CardShell className="p-6 animate-fade-up animate-delay-5">
      <div className="flex items-start justify-between mb-6">
        <CardLabel>AI Clinical Interpretation</CardLabel>
        <div className="flex items-center gap-1.5 px-2 py-1"
             style={{ background: '#201f22', border: '1px solid rgba(255,255,255,0.07)' }}>
          <span className="material-symbols-outlined text-sm" style={{ color: '#474747' }}>
            {ai.source === 'groq' ? 'neurology' : 'rule'}
          </span>
          <span style={{ fontFamily: 'JetBrains Mono', fontSize: 8, textTransform: 'uppercase', letterSpacing: '0.1em', color: '#474747' }}>
            {ai.source === 'groq' ? 'Llama 3.3 70B' : 'Rule-based'}
          </span>
        </div>
      </div>

      {/* Quote */}
      <div className="relative pl-4 mb-6" style={{ borderLeft: '2px solid rgba(255,255,255,0.15)' }}>
        {sentences.map((s, i) => (
          <p key={i}
             className={`text-sm leading-relaxed ${i > 0 ? 'mt-3' : ''}`}
             style={{ color: i === 0 ? '#e5e1e4' : '#c6c6c6', fontFamily: 'Instrument Sans' }}>
            {s}
          </p>
        ))}
      </div>

      {/* Source line */}
      <div className="flex items-center gap-2 pt-4"
           style={{ borderTop: '1px solid rgba(255,255,255,0.05)' }}>
        <span className="material-symbols-outlined text-base" style={{ color: '#474747' }}>auto_awesome</span>
        <span style={{ fontFamily: 'JetBrains Mono', fontSize: 9, textTransform: 'uppercase', letterSpacing: '0.1em', color: '#474747' }}>
          {ai.source === 'groq'
            ? `Generated by ${ai.model}`
            : 'Generated by rule-based analysis'}
        </span>
      </div>
    </CardShell>
  );
}
